#!/usr/bin/python
# coding:utf-8

import __init__  # NOQA
import sys
import cgi
import cgitb
import json
import client
import parse
cgitb.enable()
# 此脚本处理所有的通过ID进行的请求
# 	包括:
# 		startTask		B
# 		stopTask		S
# 		restartTask		R
# 		deleteTask		F
# 		getResult		G
# 		deleteResult	D
# 	参数:
# 	task_ID
# 	request


form = cgi.FieldStorage()
task_ID = int(form.getvalue("task_ID"))
request = form.getvalue("request")

if request == "B":
	data = parse.parseToBinStartTask(task_ID)
elif request == "S":
	data = parse.parseToBinStopTask(task_ID)
elif request == "R":
	data = parse.parseToBinRestartTask(task_ID)
elif request == "F":
	data = parse.parseToBinDeleteTask(task_ID)
elif request == "G":
	data = parse.parseToBinGetResult(task_ID)
elif request == "D":
	data = parse.parseToBinDeleteResult(task_ID)
else:
	sys.exit(0)
client.send(data)
data = client.recv()
# 最好判断一下,防折
if(len(data) != 0):
	data = parse.parseTo(data)

# client.close()

print "Content-type:application/json\r\n\r"
if(data[parse.MAIN_KEY[1]] == 'b'):
	respons = {"request": True}
	print(json.dumps(respons))
else:
	respons = {"request": False}
	print(json.dumps(respons))
