#!/usr/bin/python
#coding:utf-8
import sys
# 使此脚本在任何目录下都可以检测到上一层目录
# 此处使用一个小技巧,sys.path的第一个地址是当前目录
# 将其改变即可
sys.path[0] = sys.path[0].replace("/client","")

# 此脚本处理所有的通过ID进行的请求
#	包括:
#		startTask		B
#		stopTask		S
#		restartTask		R
#		deleteTask		F
#		getResult		G
#		deleteResult	D
#	参数:
#	task_ID
#	request

import parse
import cgi
import cgitb
cgitb.enable()
import json
import client

form = cgi.FieldStorage()
task_ID = int(form.getvalue("task_ID"))
request = form.getvalue("request")

if request == "B":
	data = parse.parseToBinStartTask(task_ID)
elif request == "S":
	data = parse.parseToBinStopTask(task_ID)
elif request == "R":
	data = parse.parseToBinRestartTask(Task_ID)
elif request == "F":
	data = parse.parseToBinDeleteTask(Task_ID)
elif request == "G": 
	data = parse.parseToBinGetResult(Task_ID)
elif request == "D":
	data = parse.parseToBinDeleteResult(Task_ID)
else:
	sys.exit(0)
client.send(data)
data = client.recv()
# 最好判断一下,防折
if(len(data) != 0):
	data = parse.parseTo(data)

#client.close()

print "Content-type:application/json\r\n\r"
if(data[parse.MAIN_KEY[1]] == 'b'):
	respons = {"request":True}
	print(json.dumps(respons))
else:
	respons = {"request":False}
	print(json.dumps(respons))
