#!/usr/bin/python
# coding:utf-8


import __init__  # NOQA
import parse
import cgi
import cgitb
import json
import sockets
cgitb.enable()

form = cgi.FieldStorage()
name = form.getvalue("task_name")
type = form.getvalue("task_type")
para = form.getvalue("task_para")
data = parse.parseToBinAddTask(type, name, para)
sockets.send(data)

data = sockets.recv()
data = parse.parseTo(data)
sockets.close()

print "Content-type:application/json\r\n\r"
if(data[parse.MAIN_KEY[1]] == "a"):
	respons = {"addTask": True}
	print(json.dumps(respons))
else:
	respons = {"addTask": False}
	print(json.dumps(respons))
