#!/usr/bin/python
import parse  
import cgi
import cgitb
cgitb.enable()
import json
import client


form = cgi.FieldStorage() 
data = form.getvalue("task_action")
data = parse.parseToBinAddTask(data)
client.send(data)

print "Content-type:application/json\r\n\r"
data = client.recv()
data = parse.parseTo(data,1)
client.close()
if(data[1] == "a"):
	respons = {"addTask":True}
	print(json.dumps(respons))
else:
	respons = {"addTask":False}
	print(json.dumps(respons))


