#!/usr/bin/python
# coding:utf-8
import __init__  # NOQA
import parse
import json
import common
import sockets

data = parse.parseToBinListTask()
sockets.send(data)
szBuf = sockets.recv()
sockets.close()
taskList = parse.parseToList(szBuf)
'''
for task in taskList:
	create = common.timestampToDatetime(float(task[parse.TASK_KEY[2]]))
	finish = common.timestampToDatetime(float(task[parse.TASK_KEY[3]]))
	item = {
		"task_ID"	:	task[parse.TASK_KEY[0]],
		"task_ID"	:	task[parse.TASK_KEY[0]],
		"task_ID"	:	task[parse.TASK_KEY[0]],
		"task_ID"	:	task[parse.TASK_KEY[0]],
		"task_ID"	:	task[parse.TASK_KEY[0]],
		"task_ID"	:	task[parse.TASK_KEY[0]],
		"task_ID"	:	task[parse.TASK_KEY[0]],
		"task_ID"	:	task[parse.TASK_KEY[0]],
		}
	List.append(item)
'''
json_data = json.dumps(taskList, cls=common.JsonEncoder)
print "Content-type:application/json\r\n\r"
print(json_data)
