#!/usr/bin/python
import parse  
import json
import common
import client
data = parse.parseToBinListTask()
client.send(data)
szBuf = client.recv()
client.close()
taskList = parse.parseToList(szBuf)
List = []
for task in taskList:
	timesamp = common.timestampToDatetime(float(task[2]))
	item = {
		"task_ID"	:	task[0],
		"task_state":	task[1],
		"task_date"	:	timesamp,
		"task_data"	:	task[3],
		"task_error":	task[4]
		}
	List.append(item)
json_data = json.dumps(List,cls = common.JsonEncoder)
print "Content-type:application/json\r\n\r"
print(json_data)  
