#!/usr/bin/python
#coding:utf-8
import sys
# 使此脚本在任何目录下都可以检测到上一层目录
# 此处使用一个小技巧,sys.path的第一个地址是当前目录
# 将其改变即可
sys.path[0] = sys.path[0].replace("/client","")
#sys.path.append("..")
import parse  
import json
import common
import client
data = parse.parseToBinListTask()
client.send(data)
szBuf = client.recv()
client.close()
taskList = parse.parseToList(szBuf)
'''
for task in taskList:
	create = common.timestampToDatetime(float(task[parse.TASK_KEY[2]]))
	finish = common.timestampToDatetime(float(task[parse.TASK_KEY[3]]))
	item = {
		"task_ID"	:	task[parse.TASK_KEY[0]],
		"task_ID"	:	task[parse.TASK_KEY[0]],
		"task_ID"	:	task[parse.TASK_KEY[0]],
		"task_ID"	:	task[parse.TASK_KEY[0]],
		"task_ID"	:	task[parse.TASK_KEY[0]],
		"task_ID"	:	task[parse.TASK_KEY[0]],
		"task_ID"	:	task[parse.TASK_KEY[0]],
		"task_ID"	:	task[parse.TASK_KEY[0]],
		}
	List.append(item)
'''
json_data = json.dumps(taskList,cls = common.JsonEncoder)
print "Content-type:application/json\r\n\r"
print(json_data)  
