#!/usr/bin/python
#coding:utf-8
import sys
# 使此脚本在任何目录下都可以检测到上一层目录
# 此处使用一个小技巧,sys.path的第一个地址是当前目录
# 将其改变即可
sys.path[0] = sys.path[0].replace("/client","")

import parse
import cgi
import cgitb
cgitb.enable()
import json
import client

form = cgi.FieldStorage()
task_ID = form.getvalue("task_ID")
#需要将ID转换为int

task_ID = 1
task_ID = int(task_ID)

data = parse.parseToBinStartTask(task_ID)
print(data)
client.send(data)
data = client.recv()
# 最好判断一下,防折
if(len(data) != 0):
	data = parse.parseTo(data)

#client.close()

print "Content-type:application/json\r\n\r"
if(data[parse.MAIN_KEY[1]] == 'b'):
	respons = {"startTask":True}
	print(json.dumps(respons))
else:
	respons = {"startTask":False}
	print(json.dumps(respons))
