#!/usr/bin/python
import socket
import parse  
import cgi
import cgitb
cgitb.enable()

form = cgi.FieldStorage() 
'''
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM);  
sock.connect(('localhost', 8001));  
data = parse.parseToBinAddTask("heheheehehTest123test")
sock.send(data);  

szBuf = sock.recv(1024)
data = parse.parseTo(szBuf,1)

print(data)  
sock.close();  
'''
print "Content-type:application/json\r\n\r"
print(form)
