#!/usr/bin/python
import socket
import parse  
import json
import common
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM);  
sock.connect(('localhost', 8001));  
data = parse.parseToBin("L",'')
sock.send(data);  
szBuf = sock.recv(1024)
taskList = parse.parseToList(szBuf)
sock.close();  
List = []
for task in taskList:
	timesamp = common.timestampToDatetime(float(task[2]))
	item = {
		"task_ID"	:	task[0],
		"task_state":	task[1],
		"task_date"	:	timesamp,
		"task_etc"	:	task[3]
		}
	List.append(item)
json_data = json.dumps(List,cls = common.JsonEncoder)
print "Content-type:application/json\r\n\r"
print(json_data)  
